pipeline {
    agent {
        label 'agent'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url:'https://github.com/PriyeshPandey07/bootstrap-website.git', branch: 'main'
            }
        }
         stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerpriyesh', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh '''
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                    '''
                }
            }
        }
        stage("build image")
        {
            steps {
                script {
                    sh "docker build -t avengerimg:latest ."
                }
            }
        }
        stage("run image")
        {
            steps {
                script {
                    sh "docker run -dit --name web -p 6000:80 avengerimg:latest"
                }
            }
        }
    }
}
